### ISSUE TITLE
Struggling with stress (majorization)

### ISSUE THREAD

**Issue by mbojan** [schochastics/smglr#11]
See this igraph object saved as an RDS file and ZIPped [x.rds.zip](https://github.com/schochastics/smglr/files/2690871/x.rds.zip). I'm getting really strange results with `stress_majorization()`:

```r
library(igraph)
x <- readRDS("x.rds")

xysm <- smglr::stress_majorization(x)
xyfr <- igraph::layout_with_fr(x, grid="nogrid")

plot(x, layout=xysm, vertex.label=NA, vertex.size=3)
plot(x, layout=xyfr, vertex.label=NA, vertex.size=3)
```

The two plots are:

1. stress majorization
![image](https://user-images.githubusercontent.com/636574/50160341-58a6dc80-02d9-11e9-8f46-cbac0367695e.png)

2. fruchterman-reingold
![image](https://user-images.githubusercontent.com/636574/50160368-6eb49d00-02d9-11e9-949a-cc2d05945c1f.png)

That does not seem right...

**Comment by mbojan** [comment]
And this version uses F-R as implemented in `network` (it uses simulated annealing to optimize F-R energy):

```r
xyn <- network::network.layout.fruchtermanreingold(intergraph::asNetwork(x), layout.par=NULL)
plot(x, layout=xyn, vertex.size=3, vertex.label=NA)
```

![image](https://user-images.githubusercontent.com/636574/50161010-e59e6580-02da-11e9-822c-a99d3627452f.png)

**Comment by schochastics** [comment]
I just yesterday noticed something similar too. The current implementations mixes up nodeIDs when the graph has several components. I am fixing that. Thx for the example

**Comment by schochastics** [comment]
Should be fixed now, though I can see that the arrangement of components definitely still needs some work.
![x](https://user-images.githubusercontent.com/17147355/50165260-7a559300-02dc-11e9-8e96-6ae5f0723f3f.png)

**Comment by mbojan** [comment]
Thanks! Is the arrangement up to the bin-packing algorithm?

**Comment by schochastics** [comment]
yes, but I want to implement that myself, cause I think this can be improved quite a bit. It looks far to random atm. The idea is to put the biggest component on top and the smaller ones below, sorted by size of the components.
