### ISSUE TITLE
Testthat tests

### ISSUE THREAD

**Issue by mbojan** [schochastics/smglr#4]
While fixing #3 I implemented some rudimentary tests using `testthat` package. Would like them?

Speaking of which, I can also submit TravisCI and Appveyor setup files so that `R CMD check`  is automatically run after every commit. Interested?

**Comment by schochastics** [comment]
Thanks for your suggestions/help. Just send a PR :+1:

**Comment by mbojan** [comment]
Cool. PRs incoming.

This will be my go-to network layout :) So thanks to you :)
